src/mock_facebook_app/facebook/urls.py
from django.conf.urls import patterns, url

from facebook import views


urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^verifyLogin$', views.VerifyLogin.as_view(), name='verifyLogin'),
    url(r'^verifySignUp$', views.VerifySignUp.as_view(), name='verifySignUp'),
    url(r'^login$', views.LoginUser.as_view(), name='login'),
    url(r'^post_status$', views.PostStatus.as_view(), name='post_status'),
    url(r'^remove_post$', views.RemovePost.as_view(), name='remove_post'),
    url(r'^update_post$', views.PostUpdate.as_view(), name='update_post'),
    url(r'^submit_editForm$',
        views.EditPost.as_view(),
        name='submit_editForm'),
    url(r'^toggle_like$', views.ToggleLike.as_view(), name='toggle_like'),
    url(r'^logout$', views.LogoutUser.as_view(), name='logout'),
    url(r'^(?P<slug>[\w@+._-]+)$', views.ProfileView.as_view(), name='profile')
)

src/mock_facebook_app/mock_facebook_app/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^facebook/', include('facebook.urls', namespace="facebook")),
    url(r'^admin/', include(admin.site.urls)),
)

src/mock_facebook_app/facebook/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField()
    datetime = models.DateTimeField('date posted')


class Like(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post, related_name="likes")


class Comment(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post, related_name="comments")
    text = models.TextField()
    datetime = models.DateTimeField('date posted')

src/mock_facebook_app/facebook/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username")


class PostForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'What\'s on your mind?'}
        )
    )

src/mock_facebook_app/facebook/views.py
import json
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.views import generic
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.http import HttpResponseNotFound
from django.core.serializers.json import DjangoJSONEncoder

from facebook.models import Post, Like, Comment
from facebook.forms import LoginForm, SignUpForm, PostForm


class IndexView(generic.View):

    def dispatch(self, request, *args, **kwargs):
        handler_class = None

        if request.user.is_authenticated():
            handler_class = HomeView(request=request)
        else:
            handler_class = LoginView(request=request)

        if request.method.lower() in handler_class.http_method_names:
            handler = getattr(handler_class, request.method.lower(),
                              handler_class.http_method_not_allowed)
        else:
            handler = handler_class.http_method_not_allowed
        return handler(request, *args, **kwargs)


class LoginView(generic.TemplateView):
    template_name = "facebook/login.html"

    def get_context_data(self, **kwargs):
        context = {
            'loginform': LoginForm(),
            'signupform': SignUpForm()
        }
        return context


class LoginUser(generic.TemplateView):
    template_name = "facebook/login-attempt.html"

    def get_context_data(self, **kwargs):
        error = ""
        if self.request.GET.get('login_error'):
            error = "Invalid username or password."

        context = {
            'loginform': LoginForm(),
            'error': error
        }
        return context


class HomeView(generic.TemplateView):
    template_name = "facebook/home.html"

    def get_context_data(self, **kwargs):
        posts = Post.objects.order_by('datetime').reverse()

        context = {
            'postform': PostForm(),
            'posts': posts,
        }
        return context


class RemovePost(generic.View):

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=request.POST['post-id'])

        if (post.user.id == request.user.id):
            post.delete()
            return HttpResponse(
                json.dumps({"success": True})
            )
        else:
            return HttpResponse(json.dumps({"success": False}))


class ToggleLike(generic.View):

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=request.POST['post-id'])
        like = Like.objects.filter(user=request.user, post=post)

        if like:
            post.likes.filter(user=request.user).delete()
            s = self.countLikes(request.user, post)
            return HttpResponse(
                json.dumps({"innerHTML": "Like", "newCount": s})
            )
        else:
            like = Like(user=request.user, post=post)
            like.save()
            s = self.countLikes(request.user, post)
            return HttpResponse(
                json.dumps({"innerHTML": "Unlike", "newCount": s})
            )

    def countLikes(self, user, post):
        likes = Like.objects.filter(post=post)
        n = len(likes)
        s = ""

        if n == 0:
            s = 'Be the first one to like this post.'
        elif n == 1:
            if likes.last().user == user:
                s = "You like this."
            else:
                s = likes.last().user.first_name + " likes this."
        else:
            if likes.filter(user=user):
                name = "You"
            else:
                name = likes.last().user.first_name

            s = name + " and " + str(n - 1) + " other(s) like this."

        return s


class PostUpdate(generic.View):

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=request.POST['post-id'])

        if post:
            data = {'text': post.text}
            html = render_to_string(
                "facebook/home_post_form.html",
                {"form": PostForm(initial=data),
                 "user": request.user,
                 "post": post}
            )

            return HttpResponse(html)
        else:
            return HttpResponse(json.dumps({"success": False}))


class EditPost(generic.View):

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=request.POST['post-id'])

        if post:
            post.text = request.POST['text']
            post.save()
            html = render_to_string(
                "facebook/post.html", {"post": post, "user": request.user}
            )

            return HttpResponse(html)
        else:
            return HttpResponse(json.dumps({"success": False}))


class PostStatus(generic.View):

    def post(self, request, *args, **kwargs):
        p = Post(
            user=request.user,
            text=request.POST['text'],
            datetime=timezone.now())
        p.save()

        if request.is_ajax():
            html = render_to_string(
                "facebook/post.html", {"post": p, "user": request.user}
            )
            return HttpResponse(html)

        return HttpResponseRedirect(reverse('facebook:index'))


class VerifyLogin(generic.View):

    def post(self, request, *args, **kwargs):
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )

        if user:
            login(request, user)
        else:
            return HttpResponseRedirect(
                reverse('facebook:login')+"?login_error=1"
            )

        return HttpResponseRedirect(reverse('facebook:index'))


class VerifySignUp(generic.View):

    def post(self, request, *args, **kwargs):
        user_form = SignUpForm(request.POST)
        if user_form.is_valid():
            username = user_form.clean_username()
            password = user_form.clean_password2()
            user_form.save()
            user = authenticate(username=username,
                                password=password)
            login(request, user)
            if request.is_ajax():
                return HttpResponse('{"success": true}')
        else:
            s = "Error:\n"

            for keys in user_form.error_messages:
                s += user_form.error_messages[keys] + "\n"

            if request.is_ajax():
                return HttpResponse(
                    json.dumps({"success": "false", "error": user_form.errors})
                )

        return HttpResponseRedirect(reverse('facebook:index'))


class LogoutUser(generic.View):

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('facebook:index'))


class ProfileView(generic.DetailView):
    model = User
    template_name = "facebook/profile.html"

    def get_object(self, **kwargs):
        return get_object_or_404(User, username=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = {
            'userprofile': self.object,
            'posts': Post.objects.filter(user=self.object)
        }
        return context

src/mock_facebook_app/facebook/templates/facebook/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load facebook_tags %}

{% block post %}
<form id="post-form" method="POST">
    {% csrf_token %}
    {{ postform.text }}
    <button type="submit" class="uibutton confirm" id="post-button">Post</button>
</form>
{% endblock %}

{% block feed %}
    {% for item in posts %}
        <div id="container_{{ item.id }}" class="stat-container">
            <div class="picture">
                <img id="profpic" src="{% static 'facebook/images/prof-pic.png' %}"/>
                <a href="/facebook/{{item.user}}">{{ item.user.first_name }}</a>
            </div>
            <div class="bubble">
                {{ item.text|linebreaksbr }}
                <div class="toggleLikeContainer">
                    {% has_liked user item %}
                    <span class="likeCount"> {% count_likes user item %} </span>
                </div>
                <div class="datetimeContainer">
                    {{ item.datetime | time:"g:i A -" | lower }}
                    {{ item.datetime | date:"M d, Y"}}
                </div>
                {% if item.user.id == user.id %}
                <div class="removePostContainer">
                    <a href="" class="editPost" name="{{ item.id }}">Edit</a>
                    |
                    <a href="#" id="{{ item.id }}" class="removePost">x</a>
                </div>
                {% endif %}
            </div>
        </div> 
    {% endfor %}
{% endblock %}

src/mock_facebook_app/facebook/templates/facebook/home_post_form.html
<form id="update-post-form" method="post">
    {% csrf_token %}
    {{ form.text }}
    <br>
    <button type="submit" class="uibutton confirm" id="update-button" value="{{post.id}}">Edit</button>
</form>

src/mock_facebook_app/facebook/templates/facebook/login-attempt.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Facebook</title>
        <link rel="stylesheet" type="text/css" href="{% static 'facebook/css/fb-buttons.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'facebook/css/application.css' %}">
    </head>
    <body>
        <div id="header-container">
            <div class="wrapper">
                <div id="logo">
                    <h1><a href="/facebook/">facebook</a></h1>
                </div>
            </div>
        </div>
        <div id="body-container">
            <div class="wrapper">
                <div id="global-container">
                    <div id="login-attempt-container">
                        <div id="login-attempt-header">
                            <h2>Facebook login</h2>
                            <br>
                        </div>
                        <div id="login-container">
                            <form id="login-attempt" action="{% url 'facebook:verifyLogin' %}" method="POST" style="margin-top: 50px;">
                                {% csrf_token %}
                                {% if error != "" %}
                                    <div class="error-message" style="margin-bottom:30px">{{ error }}</div>
                                {% endif %}

                                <table id="login-form">
                                    <tr>
                                        <td style="color:black">Username</td>
                                        <td style="color:black">Password</td>
                                    </tr>
                                    <tr>
                                        <td>{{ loginform.username }}</td>
                                        <td>{{ loginform.password }}</td>
                                        <td><button type="submit" id="login-button" class="uibutton confirm" value="Login" />Login</td>
                                    </tr>
                                </table>
                            </form>
                        <div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'facebook/js/jquery.js' %}"></script>
        <script type="text/javascript">
            var verifyLoginURL = '{% url "facebook:verifyLogin" %}';
            var verifySignUpURL ='{% url "facebook:verifySignUp" %}';
            var loginURL = '{% url "facebook:login" %}';
        </script>
        <script type="text/javascript" src="{% static 'facebook/js/application.js' %}"></script>
    </body>
</html>

src/mock_facebook_app/facebook/templates/facebook/login.html
{% extends "splash-screen.html" %}

{% block login %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form id="login" method="POST" action="{% url 'facebook:verifyLogin' %}">
    {% csrf_token %}
    <table id="login-form">
        <tr>
            <td>Username</td>
            <td>Password</td>
        </tr>
        <tr>
            <td>{{ loginform.username }}</td>
            <td>{{ loginform.password }}</td>
            <td><button type="submit" id="login-button" class="uibutton confirm" value="Login" />Login</td>
        </tr>
    </table>
</form>

{% endblock %}

{% block signup %}
<div id="sign-up"> 
    <h2>Sign Up</h2>
    <p>It's free and always will be.</p>
    <form id="signup" method="POST">
        {% csrf_token %}
        <table id="signup-form">
            {{signupform}}
        </table>
        <td><button type="submit" id="signup-button" class="uibutton large special" value="Sign Up">Sign Up</button></td>
    </form>
</div>
{% endblock %}

src/mock_facebook_app/facebook/templates/facebook/post.html
{% load staticfiles %}
{% load facebook_tags %}


<div id="container_{{ post.id }}" class="stat-container">
    <div class="picture">
        <img id="profpic" src="{% static 'facebook/images/prof-pic.png' %}"/>
        <a href="/facebook/{{post.user}}">{{ post.user.first_name }}</a>
    </div>
    <div class="bubble">
        {{ post.text|linebreaksbr }}
        <div class="toggleLikeContainer">
            {% has_liked user post %}
            <span class="likeCount"> {% count_likes user post %} </span>
        </div>
        <div class="datetimeContainer">
            {{ post.datetime | time:"g:i A -" | lower }}
            {{ post.datetime | date:"M d, Y"}}
        </div>
        {% if post.user.id == user.id %}
        <div class="removePostContainer">
            <a href="" class="editPost" name="{{ post.id }}">Edit</a>
            |
            <a href="#" id="{{ post.id }}" class="removePost">x</a>
        </div>
        {% endif %}
    </div>
</div> 

src/mock_facebook_app/facebook/templates/facebook/profile.html
{% load staticfiles %}
{% load facebook_tags %}


{% if user.is_authenticated%}
    <!DOCTYPE html>
    <html>
        <head>  
            <title>Facebook</title>
            <link rel="stylesheet" type="text/css" href="{% static 'facebook/css/fb-buttons.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'facebook/css/application.css' %}">
        </head>
        <body>
            <div id="header-container">
                <div class="wrapper">
                    <div id="logo">
                        <h1><a href="/facebook/">facebook</a></h1>
                    </div>
                    <div id="content-container">
                        <div id="greeting">
                            <span>Hi, {{ user.first_name }}!</span>
                            <a href="{% url 'facebook:logout' %}" class="uibutton confirm" id="logout-button">Logout</a>
                        </div>
                    </div> 
                </div>
            </div>
            <div id="body-container">
                <div class="wrapper">
                    <div id="post-status-container">
                        <div id="post-status" style="text-align: center">
                            <img id="profpic" src="{% static 'facebook/images/prof-pic.png' %}" style="height:100px;width:100px"/>
                            <h3>{{ userprofile.first_name }} {{ userprofile.last_name }}</h3>   
                        </div>
                    </div>
                    <div id="posts-container">
                        <div id="posts">
                            {% if not posts %}
                                <div style="text-align: center"><h3>No posts to show.</h3></div>
                            {% endif %}
                            {% for item in posts %}
                                <div id="container_{{ item.id }}" class="stat-container">
                                    <div class="picture">
                                        <img id="profpic" src="{% static 'facebook/images/prof-pic.png' %}"/>
                                        {{ item.user.first_name }}
                                    </div>
                                    <div class="bubble">
                                        {{ item.text|linebreaksbr }}
                                        <div class="toggleLikeContainer">
                                            {% has_liked user item %}
                                            <span class="likeCount"> {% count_likes user item %} </span>
                                        </div>
                                        <div class="datetimeContainer">
                                            {{ item.datetime | time:"g:i A -" | lower }}
                                            {{ item.datetime | date:"M d, Y"}}
                                        </div>
                                        {% if item.user.id == user.id %}
                                        <div class="removePostContainer">
                                            <a href="" class="editPost" name="{{ item.id }}">Edit</a>
                                            |
                                            <a href="#" id="{{ item.id }}" class="removePost">x</a>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div> 
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript" src="{% static 'facebook/js/jquery.js' %}"></script>
            <script type="text/javascript">
                var postStatusURL = "{% url 'facebook:post_status' %}";
                var removePostURL = "{% url 'facebook:remove_post' %}";
                var toggleLikeURL = "{% url 'facebook:toggle_like' %}";
                var updatePostURL = "{% url 'facebook:update_post' %}";
                var submitEditFormURL = "{% url 'facebook:submit_editForm' %}"
            </script>
            <script type="text/javascript" src="{% static 'facebook/js/application.js' %}"></script>
        </body>
    </html>
{% else %}
    <h3>You need to login to see {{ userprofile.first_name }}'s profile.</h3>
{% endif %} 